---
name: Build - Ubuntu

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - devel
      - develop
      - canary-client

env:
  VCPKG_BUILD_TYPE: release
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        buildtype: [Debug, RelWithDebInfo]
        include:
          - os: ubuntu-20.04
            triplet: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ubuntu - install packages
        run: sudo apt-get install libglew-dev libluajit-5.1-dev

      - name: CCache
        id: ccache
        uses: actions/cache@v2
        with:
          path: /home/runner/.ccache
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}-${{ hashFiles('**/src') }}
          restore-keys: |
            ccache-${{ matrix.os }}-${{ matrix.buildtype }}-
            ccache-${{ matrix.os }}-

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v7
        with:
          setupOnly: true
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ github.workspace }}/build/vcpkg_installed
          vcpkgGitCommitId: 9a49e3df7f729655318c59b9985c9c18ad0c99d6

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build with CMake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: ${{ github.workspace }}/CMakeLists.txt
          useVcpkgToolchainFile: true
          buildDirectory: ${{ github.workspace }}/build
          cmakeBuildType: ${{ matrix.buildtype }}
